// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXEsQ47lULzocTPCb8jiSiAKHRjwMSi_Q',
    appId: '1:601682043196:web:5e07faa676619b40d4be39',
    messagingSenderId: '601682043196',
    projectId: 'tset-firebase77',
    authDomain: 'tset-firebase77.firebaseapp.com',
    storageBucket: 'tset-firebase77.firebasestorage.app',
    measurementId: 'G-QFN3MKSYNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEtsGYt6wYn1p3FvLb67hvmA4sF2pS4ts',
    appId: '1:601682043196:android:3598cb4d05718a8fd4be39',
    messagingSenderId: '601682043196',
    projectId: 'tset-firebase77',
    storageBucket: 'tset-firebase77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPlfVALQe4q6Lir0V2YPKHND0hlDxH6A',
    appId: '1:601682043196:ios:f3ab45675aa7b49fd4be39',
    messagingSenderId: '601682043196',
    projectId: 'tset-firebase77',
    storageBucket: 'tset-firebase77.firebasestorage.app',
    androidClientId: '601682043196-42mjeia284vm4tl3oumb9quprtfc0cpe.apps.googleusercontent.com',
    iosClientId: '601682043196-g6f4313skvna9dsd56sm67g3gvdqcah8.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPlfVALQe4q6Lir0V2YPKHND0hlDxH6A',
    appId: '1:601682043196:ios:f3ab45675aa7b49fd4be39',
    messagingSenderId: '601682043196',
    projectId: 'tset-firebase77',
    storageBucket: 'tset-firebase77.firebasestorage.app',
    androidClientId: '601682043196-42mjeia284vm4tl3oumb9quprtfc0cpe.apps.googleusercontent.com',
    iosClientId: '601682043196-g6f4313skvna9dsd56sm67g3gvdqcah8.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXEsQ47lULzocTPCb8jiSiAKHRjwMSi_Q',
    appId: '1:601682043196:web:35a534ae38f20fb7d4be39',
    messagingSenderId: '601682043196',
    projectId: 'tset-firebase77',
    authDomain: 'tset-firebase77.firebaseapp.com',
    storageBucket: 'tset-firebase77.firebasestorage.app',
    measurementId: 'G-DXYQ9J0PDV',
  );

}